const fs = require('fs');
const path = require('path');

// Target the exams folder and the master index file
const examsDir = path.join(__dirname, 'src/config/exams');
const indexPath = path.join(__dirname, 'src/config/index.ts');

// Scan the folder for all TypeScript files
const files = fs.readdirSync(examsDir).filter(file => file.endsWith('.ts'));

// Start writing the new index.ts file
let importStatements = `// AUTO-GENERATED BY BUILD SCRIPT: DO NOT EDIT MANUALLY\nimport { FormatConfig } from './formats';\n\n`;
let exportArray = `export const FORMATS: FormatConfig[] = [\n`;

files.forEach(file => {
  const examId = file.replace('.ts', '');
  const configName = `${examId}Config`; 
  importStatements += `import { ${configName} } from './exams/${examId}';\n`;
  exportArray += `  ${configName},\n`;
});

exportArray += `];\n`;

// Overwrite the index.ts file with the new data
fs.writeFileSync(indexPath, importStatements + exportArray);
console.log(`🚀 Database Engine wired! Auto-registered ${files.length} configurations.`);