// AUTO-GENERATED BY BUILD SCRIPT: DO NOT EDIT MANUALLY
import { FormatConfig } from './formats';

import { afmc_mbbsConfig } from './exams/afmc_mbbs';
import { ap_eapcetConfig } from './exams/ap_eapcet';
import { bitsatConfig } from './exams/bitsat';
import { comedk_ugetConfig } from './exams/comedk_uget';
import { gujcetConfig } from './exams/gujcet';
import { ini_cetConfig } from './exams/ini_cet';
import { jee_advancedConfig } from './exams/jee_advanced';
import { jee_mainConfig } from './exams/jee_main';
import { kcetConfig } from './exams/kcet';
import { keamConfig } from './exams/keam';
import { met_manipalConfig } from './exams/met_manipal';
import { mht_cetConfig } from './exams/mht_cet';
import { neet_pgConfig } from './exams/neet_pg';
import { neet_ugConfig } from './exams/neet_ug';
import { ojeeConfig } from './exams/ojee';
import { srmjeeeConfig } from './exams/srmjeee';
import { ssc_cglConfig } from './exams/ssc_cgl';
import { ssc_chslConfig } from './exams/ssc_chsl';
import { ssc_gdConfig } from './exams/ssc_gd';
import { ssc_jeConfig } from './exams/ssc_je';
import { ssc_mtsConfig } from './exams/ssc_mts';
import { ssc_stenographerConfig } from './exams/ssc_stenographer';
import { ts_eamcetConfig } from './exams/ts_eamcet';
import { viteeeConfig } from './exams/viteee';
import { wbjeeConfig } from './exams/wbjee';
export const FORMATS: FormatConfig[] = [
  afmc_mbbsConfig,
  ap_eapcetConfig,
  bitsatConfig,
  comedk_ugetConfig,
  gujcetConfig,
  ini_cetConfig,
  jee_advancedConfig,
  jee_mainConfig,
  kcetConfig,
  keamConfig,
  met_manipalConfig,
  mht_cetConfig,
  neet_pgConfig,
  neet_ugConfig,
  ojeeConfig,
  srmjeeeConfig,
  ssc_cglConfig,
  ssc_chslConfig,
  ssc_gdConfig,
  ssc_jeConfig,
  ssc_mtsConfig,
  ssc_stenographerConfig,
  ts_eamcetConfig,
  viteeeConfig,
  wbjeeConfig,
];
