// AUTO-GENERATED BY BUILD SCRIPT: DO NOT EDIT MANUALLY
import { FormatConfig } from './formats';

import { afcatConfig } from './exams/afcat';
import { afmc_mbbsConfig } from './exams/afmc_mbbs';
import { ailetConfig } from './exams/ailet';
import { ap_eapcetConfig } from './exams/ap_eapcet';
import { bihar_police_constableConfig } from './exams/bihar_police_constable';
import { bihar_stetConfig } from './exams/bihar_stet';
import { bitsatConfig } from './exams/bitsat';
import { bpscConfig } from './exams/bpsc';
import { catConfig } from './exams/cat';
import { clatConfig } from './exams/clat';
import { cmatConfig } from './exams/cmat';
import { comedk_ugetConfig } from './exams/comedk_uget';
import { csir_netConfig } from './exams/csir_net';
import { ctetConfig } from './exams/ctet';
import { cuet_pgConfig } from './exams/cuet_pg';
import { cuet_ugConfig } from './exams/cuet_ug';
import { delhi_police_constableConfig } from './exams/delhi_police_constable';
import { gujcetConfig } from './exams/gujcet';
import { haryana_police_constableConfig } from './exams/haryana_police_constable';
import { hpscConfig } from './exams/hpsc';
import { hp_police_constableConfig } from './exams/hp_police_constable';
import { htetConfig } from './exams/htet';
import { ibps_clerkConfig } from './exams/ibps_clerk';
import { ibps_poConfig } from './exams/ibps_po';
import { ibps_rrbConfig } from './exams/ibps_rrb';
import { iiftConfig } from './exams/iift';
import { indian_airforce_agniveervayuConfig } from './exams/indian_airforce_agniveervayu';
import { indian_army_agniveerConfig } from './exams/indian_army_agniveer';
import { indian_navy_ssrConfig } from './exams/indian_navy_ssr';
import { ini_cetConfig } from './exams/ini_cet';
import { jee_advancedConfig } from './exams/jee_advanced';
import { jee_mainConfig } from './exams/jee_main';
import { kcetConfig } from './exams/kcet';
import { keamConfig } from './exams/keam';
import { kpsc_karConfig } from './exams/kpsc_kar';
import { kpsc_keralaConfig } from './exams/kpsc_kerala';
import { ktetConfig } from './exams/ktet';
import { maharashtra_police_bhartiConfig } from './exams/maharashtra_police_bharti';
import { matConfig } from './exams/mat';
import { met_manipalConfig } from './exams/met_manipal';
import { mht_cetConfig } from './exams/mht_cet';
import { mppscConfig } from './exams/mppsc';
import { mpscConfig } from './exams/mpsc';
import { mp_police_constableConfig } from './exams/mp_police_constable';
import { nchm_jeeConfig } from './exams/nchm_jee';
import { neet_pgConfig } from './exams/neet_pg';
import { neet_ugConfig } from './exams/neet_ug';
import { nid_datConfig } from './exams/nid_dat';
import { nift_entranceConfig } from './exams/nift_entrance';
import { nmatConfig } from './exams/nmat';
import { ojeeConfig } from './exams/ojee';
import { rajasthan_policeConfig } from './exams/rajasthan_police';
import { rbi_assistantConfig } from './exams/rbi_assistant';
import { rbi_grade_bConfig } from './exams/rbi_grade_b';
import { reetConfig } from './exams/reet';
import { rpf_constableConfig } from './exams/rpf_constable';
import { rpf_siConfig } from './exams/rpf_si';
import { rpscConfig } from './exams/rpsc';
import { rrb_group_dConfig } from './exams/rrb_group_d';
import { rrb_jeConfig } from './exams/rrb_je';
import { rrb_ntpcConfig } from './exams/rrb_ntpc';
import { sbi_clerkConfig } from './exams/sbi_clerk';
import { sbi_poConfig } from './exams/sbi_po';
import { snapConfig } from './exams/snap';
import { srmjeeeConfig } from './exams/srmjeee';
import { ssc_cglConfig } from './exams/ssc_cgl';
import { ssc_chslConfig } from './exams/ssc_chsl';
import { ssc_gdConfig } from './exams/ssc_gd';
import { ssc_jeConfig } from './exams/ssc_je';
import { ssc_mtsConfig } from './exams/ssc_mts';
import { ssc_stenographerConfig } from './exams/ssc_stenographer';
import { tnpscConfig } from './exams/tnpsc';
import { ts_eamcetConfig } from './exams/ts_eamcet';
import { ugc_netConfig } from './exams/ugc_net';
import { uppscConfig } from './exams/uppsc';
import { upsc_capfConfig } from './exams/upsc_capf';
import { upsc_cdsConfig } from './exams/upsc_cds';
import { upsc_cseConfig } from './exams/upsc_cse';
import { upsc_eseConfig } from './exams/upsc_ese';
import { upsc_ndaConfig } from './exams/upsc_nda';
import { uptetConfig } from './exams/uptet';
import { up_police_constableConfig } from './exams/up_police_constable';
import { viteeeConfig } from './exams/viteee';
import { wbjeeConfig } from './exams/wbjee';
import { xatConfig } from './exams/xat';
export const FORMATS: FormatConfig[] = [
  afcatConfig,
  afmc_mbbsConfig,
  ailetConfig,
  ap_eapcetConfig,
  bihar_police_constableConfig,
  bihar_stetConfig,
  bitsatConfig,
  bpscConfig,
  catConfig,
  clatConfig,
  cmatConfig,
  comedk_ugetConfig,
  csir_netConfig,
  ctetConfig,
  cuet_pgConfig,
  cuet_ugConfig,
  delhi_police_constableConfig,
  gujcetConfig,
  haryana_police_constableConfig,
  hpscConfig,
  hp_police_constableConfig,
  htetConfig,
  ibps_clerkConfig,
  ibps_poConfig,
  ibps_rrbConfig,
  iiftConfig,
  indian_airforce_agniveervayuConfig,
  indian_army_agniveerConfig,
  indian_navy_ssrConfig,
  ini_cetConfig,
  jee_advancedConfig,
  jee_mainConfig,
  kcetConfig,
  keamConfig,
  kpsc_karConfig,
  kpsc_keralaConfig,
  ktetConfig,
  maharashtra_police_bhartiConfig,
  matConfig,
  met_manipalConfig,
  mht_cetConfig,
  mppscConfig,
  mpscConfig,
  mp_police_constableConfig,
  nchm_jeeConfig,
  neet_pgConfig,
  neet_ugConfig,
  nid_datConfig,
  nift_entranceConfig,
  nmatConfig,
  ojeeConfig,
  rajasthan_policeConfig,
  rbi_assistantConfig,
  rbi_grade_bConfig,
  reetConfig,
  rpf_constableConfig,
  rpf_siConfig,
  rpscConfig,
  rrb_group_dConfig,
  rrb_jeConfig,
  rrb_ntpcConfig,
  sbi_clerkConfig,
  sbi_poConfig,
  snapConfig,
  srmjeeeConfig,
  ssc_cglConfig,
  ssc_chslConfig,
  ssc_gdConfig,
  ssc_jeConfig,
  ssc_mtsConfig,
  ssc_stenographerConfig,
  tnpscConfig,
  ts_eamcetConfig,
  ugc_netConfig,
  uppscConfig,
  upsc_capfConfig,
  upsc_cdsConfig,
  upsc_cseConfig,
  upsc_eseConfig,
  upsc_ndaConfig,
  uptetConfig,
  up_police_constableConfig,
  viteeeConfig,
  wbjeeConfig,
  xatConfig,
];
