import { CountryVisaConfig } from './types';

export const chinaVisaConfig: CountryVisaConfig = {
    id: "china-visa",
    country: "China",
    countryCode: "CN",
    defaultProfileId: "china-visa-photo",
    profiles: [
        {
            id: "china-visa-photo",
            title: "China Visa Photo",
            country: "China",
            countryCode: "CN",
            type: "visa",
            channel: "both",
            applicableCategories: [
                "L (Tourist)",
                "Q2 (Short-term family visit)",
                "S2 (Short-term personal matters/dependent)",
                "M (Commercial trade)",
                "F (Non-commercial exchange, study tours)",
                "X1 (Long-term study >180 days)",
                "X2 (Short-term study <180 days)",
                "Z (Work)",
                "G (Transit)",
                "C (Crewmember)",
                "Q1 (Family reunion >180 days)",
                "S1 (Dependent >180 days)",
                "D (Permanent Residence Visa)",
                "R (High-level talent)",
                "M (Business/Investor)",
                "J1 (Resident foreign journalist)",
                "J2 (Temporary foreign journalist)",
                "Port Visas"
            ],
            aspectRatio: 0.6875,
            physical: {
                widthMm: 33,
                heightMm: 48,
                targetDpi: 300,
                paperFinish: "glossy",
                copiesRequired: 1,
                printSheetSize: "4x6",
                backSideRequired: false
            },
            digital: {
                minWidthPx: 354,
                minHeightPx: 472,
                maxWidthPx: 420,
                maxHeightPx: 560,
                minKb: 40,
                maxKb: 120,
                allowedFormats: ["JPEG"],
                colorSpace: "24-bit RGB"
            },
            signature: {
                required: false
            },
            passportScan: {
                required: true,
                allowedFormats: ["JPEG", "PDF"]
            },
            background: {
                requiredHex: "#FFFFFF",
                label: "Pure White"
            },
            biometrics: {
                headRatioMin: 0.58,
                headRatioMax: 0.69,
                eyeLinePercentFromBottom: 60,
                shouldersVisible: true,
                glassesAllowed: true,
                smileAllowed: false,
                contrastWarning: true
            },
            infantRules: {
                applicable: true,
                relaxedConstraints: "Infants under 6 months are allowed to have eyes closed and mouth open; no other people, hands, toys, or pacifiers allowed in the frame"
            },
            sourceVerification: {
                authority: "Consular Department of the Ministry of Foreign Affairs of the P.R. China / COVA (China Online Visa Application)",
                officialUrl: "https://www.visaforchina.cn/SYD3_EN/qianzhengyewu/jichuzhishi/changjianwenti/355135188537315328.html",
                lastVerifiedDate: "2026-09",
                disclaimer: "Prepared according to official government visa photo guidelines. Final acceptance rests with the reviewing embassy or consular authority."
            },
            seo: {
                metaTitle: "China Visa Photo Size & Official Requirements",
                metaDescription: "Official China visa photo size is 33x48 mm (1.30 x 1.89 inches). Learn the exact COVA digital upload requirements, background color rules, and biometric specifications.",
                keywords: [
                    "China visa photo size",
                    "China visa photo requirements",
                    "COVA photo upload",
                    "33x48 mm visa photo",
                    "China L visa photo",
                    "Chinese visa photo dimensions",
                    "China digital visa photo"
                ]
            }
        },
        {
            id: "china-foreign-permanent-resident-id-card",
            title: "China Foreign Permanent Resident ID Card (Five-Star Card)",
            country: "China",
            countryCode: "CN",
            type: "visa",
            channel: "both",
            applicableCategories: [
                "Foreign Permanent Resident ID Card (Five-Star Card / Chinese Green Card)"
            ],
            aspectRatio: 0.6875,
            physical: {
                widthMm: 33,
                heightMm: 48,
                targetDpi: 300,
                paperFinish: "glossy",
                copiesRequired: 4,
                printSheetSize: "4x6",
                backSideRequired: true,
                backSideInstructions: "Must typically be accompanied by a validated Digital Photo Receipt (照片回执) generated by a PSB-certified photo system."
            },
            digital: {
                minWidthPx: 354,
                minHeightPx: 472,
                maxWidthPx: 420,
                maxHeightPx: 560,
                minKb: 40,
                maxKb: 120,
                allowedFormats: ["JPEG"],
                colorSpace: "24-bit RGB"
            },
            signature: {
                required: false
            },
            passportScan: {
                required: true,
                maxKb: 2048,
                allowedFormats: ["JPEG", "PDF"]
            },
            background: {
                requiredHex: "#FFFFFF",
                label: "Pure White"
            },
            biometrics: {
                headRatioMin: 0.58,
                headRatioMax: 0.69,
                eyeLinePercentFromBottom: 60,
                shouldersVisible: true,
                glassesAllowed: true,
                smileAllowed: false,
                contrastWarning: true
            },
            infantRules: {
                applicable: true,
                relaxedConstraints: "Relaxed constraints for infants under 6 months (e.g., eyes closed permitted)."
            },
            sourceVerification: {
                authority: "National Immigration Administration (NIA) / Public Security Bureau (PSB)",
                officialUrl: "https://www.nia.gov.cn/",
                lastVerifiedDate: "2026-09",
                disclaimer: "Prepared according to official government visa photo guidelines. Final acceptance rests with the reviewing embassy or consular authority."
            },
            seo: {
                metaTitle: "China Permanent Resident ID Card Photo Requirements",
                metaDescription: "Official photo specifications for the China Foreign Permanent Resident ID Card (Five-Star Card). Requires a 33x48 mm (1.30 x 1.89 inches) size printed photograph on glossy paper.",
                keywords: [
                    "China Five-Star Card photo",
                    "China Permanent Resident ID photo",
                    "Chinese green card photo size",
                    "NIA permanent resident photo",
                    "33x48 mm ID photo",
                    "China PR card photo specs"
                ]
            }
        }
    ]
};